version: 2
updates:

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:00"
      timezone: "Europe/Paris"
    rebase-strategy: "auto"
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    groups:
      security: { applies-to: security-updates }
      symfony:  { patterns: ["symfony/*"] }
      doctrine: { patterns: ["doctrine/*", "doctrine/*-*"] }
      others-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:05"
      timezone: "Europe/Paris"
    rebase-strategy: "auto"
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    groups:
      security: { applies-to: security-updates }
      build-tools: { patterns: ["@symfony/webpack-encore*", "webpack*", "babel*"] }
      front-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:10"
      timezone: "Europe/Paris"
    rebase-strategy: "auto"
    groups:
      runtime:
        patterns:
          - "php*"
      databases-and-tools:
        patterns:
          - "mariadb*"
          - "mysql*"
          - "mongo*"
          - "mongo-express*"
          - "phpmyadmin*"
      security: { applies-to: security-updates }

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:15"
      timezone: "Europe/Paris"
    rebase-strategy: "auto"
